### ISSUE TITLE
zoomToSelected gives timeOut

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#139]

**Comment by LindaVels** [comment]
The API call zoomToSelected results in a TimeOut ini the client. In the geoide-web-service the following is logged:
09:59:08.866 [service-akka.actor.default-dispatcher-4] INFO  akka.actor.EmptyLocalActorRef - Message [nl.idgis.geoide.commons.domain.service.messages.QueryFeatures] from Actor[akka.tcp://application@1
27.0.0.1:2553/temp/$1c] to Actor[akka://service/user/serviceManager#633004024] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings '
akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by erikorbons** [comment]
Ik vermoed dat je hier ook op zoek moet naar een NotSerialisableException in de log van de service (hier boven staat de log van de Play-applicatie) die betrekking heeft op de return value van deze aanroep.

**Comment by LindaVels** [comment]
16:00:55.189 [service-akka.actor.default-dispatcher-25] ERROR application - Service nl.idgis.geoide.commons.domain.ServiceIdentification@85858f4b raised an error UNSUPPORTED_OPERATION with request: http://localhost:8080/crs-deegree-webservices/services/crs2_wfs Message: Unsupported message type: nl.idgis.geoide.commons.domain.service.messages.QueryFeatures
