### ISSUE TITLE
specialIdentify gives timeOut

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#140]

**Comment by LindaVels** [comment]
post request
http://localhost:9000/query

with:
{"layers":[{"id":"afd-afdelingen","query":null,"state":{"query":"Select b.*, 'false' as sel, 'false'
 as label from (select afdeling as id, afdeling, ogr_geometry as geom from afdelingen where ogr_geometry
.STDistance(geometry::STGeomFromText('POINT(201836.95999999996 401752.48000000004)', 28992 )) < 40.32
) as b"}}],"intersects":null,"query":null}

results in a TimeOutException in the client.

In geoide-web-service:
10:04:11.156 [service-akka.actor.default-dispatcher-14] INFO  akka.actor.EmptyLocalActorRef - Message [nl.idgis.geoide.commons.domain.service.messages.ServiceRequest] from Actor[akka.tcp://application
@127.0.0.1:2553/temp/$oe] to Actor[akka://service/user/serviceManager#633004024] was not delivered. [9] dead letters encountered. This logging can be turned off or adjusted with configuration settings
 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by erikorbons** [comment]
Idem: zie #139
