### ISSUE TITLE
tiled PDOK layer doesnot always show

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#142]

**Comment by LindaVels** [comment]
Sometimes the requests for tiles give timeoutExceptions in the client. The geoide-web-service  logs

10:19:22.686 [service-akka.actor.default-dispatcher-15] INFO  akka.actor.EmptyLocalActorRef - Message [nl.idgis.geoide.commons.domain.service.messages.ServiceRequest] from Actor[akka.tcp://application
@127.0.0.1:2553/temp/$Ih] to Actor[akka://service/user/serviceManager#633004024] was not delivered. [10] dead letters encountered, no more dead letters will be logged. This logging can be turned off o
r adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

see also #139 en #140

**Comment by erikorbons** [comment]
Deze kan ik niet direct plaatsen, het bovenstaande lijkt me een secundaire fout. De log van de service kan meer inzicht bieden.

**Comment by LindaVels** [comment]
Fout is niet meer voorgekomen, ws een secundair effect van andere reeds opgeloste problemen.
