### ISSUE TITLE
Improve Error handling

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#150]

**Comment by LindaVels** [comment]
Especially print error handling

**Comment by erikorbons** [comment]
Areas to improve:

- [ ] errors when downloading related content for a print must be reported as a failure when printing. Especially SVG content. Errors can come from the document cache or from the underlying HTTP transport.
- [ ] akka remote transport must be improved: some exceptions in the service lead to timeouts in communication. The original exception should be communicated instead.
- [ ] failures during service requests (print, query, etc.) must be reported to the user.

**Comment by erikorbons** [comment]
Nieuw event naar FoxPro geïntroduceerd: ``onPrintError``. Wordt geraised wanneer het printen om wat voor reden dan ook mislukt. Bij de aanroep is een vertaalde tekst beschikbaar als argument, dit argument wordt niet meegegeven wanneer er geen tekst kon worden vastgesteld.

**Comment by erikorbons** [comment]
Print errors should raise ``onError``, the ``onPrintError`` event is unneeded.
