### ISSUE TITLE
Update naar OpenLayers ~~3.7.0~~ 3.8.2

### ISSUE THREAD

**Issue by erikorbons** [IDgis/geoide-commons#165]
Bevat veel nuttige bugfixes, maar ook een paar relevante wijzigingen in de API. o.a.:

- ol.View.fitExtent is vervangen door ol.view.fit

**Comment by LindaVels** [comment]
Update to 3.8.2: 3.7.0 is broken.

**Comment by HermanAssink** [comment]
O.a. selectiegeometrie wordt niet verwijderd.

**Comment by LindaVels** [comment]
- [x] selectie geometrie verwijderen
- [x] Shift + Interaction werkend maken

**Comment by LindaVels** [comment]
selectie geometrie tekenen met een zeer lichte style zodat de geometrie niet storend in beeld komt
