### ISSUE TITLE
Print requests cause timeout

### ISSUE THREAD

**Issue by erikorbons** [IDgis/geoide-commons#172]
Long running print/report requests cause a timeout in the Akka remote transport layer.

Print requests can take a long time to complete, especially when remote media is downloaded (from remote map services) or when print requests are queued.

Using a timeout for the entire print request is unrealistic: requests can (theoretically) 
complete within seconds or minutes.

Proposed solution: print requests return an event stream, where the last event in the stream contains a reference to the resulting document.

**Comment by LindaVels** [comment]
Probleem heeft zich tijdens testen niet meer voorgedaan
