### ISSUE TITLE
Add DelegatingStore (with FileStore and httpDocumentStore) to StoredImageProvider

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#202]

**Comment by LindaVels** [comment]
combine both to make also getLegend request possible for legend images

**Comment by LindaVels** [comment]
When this is realized the Symbol class from the TOC can get expanded with an GetLegendGraphic url that can be read from the Capabilities

**Comment by LindaVels** [comment]
The GetLegenGraphic url is filled by the geoide-admin, no need to read it from the capabilities in the viewer. 

DelegatingStore is implemented for getting the legendGraphic. It combine a Filestore and an httpStore.

**Comment by HermanAssink** [comment]
Done?
