### ISSUE TITLE
change configpath image files / Viewer moeten blijven werken zonder Composer met json files

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#205]
In TocConfig.java change "geoide.service.components.mapProvider.configDir" in "geoide.service.components.imageProvider.dir"

**Comment by HermanAssink** [comment]
Is de viewer getest met config in json en png files? O.a. i.v.m. CA3 klanten

**Comment by LindaVels** [comment]
ja, dat blijft werken. Zag wel dat op de testomgeving nog geen images voor de legenda staan voor bijv Overwater. Hoe zit dat op de productie omgeving?

**Comment by LindaVels** [comment]
printen nog niet kunnen testen: zie issue printen

**Comment by LindaVels** [comment]
Op de test omgeving Overwater nieuwe viewer geïnstalleerd, hiermee kan de viewer zonder geoide-composer getest worden.
