### ISSUE TITLE
Tilesets cannot be found for pdok TMS with limited levels

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#211]
http://geodata.nationaalgeoregister.nl/tms/1.0.0/top25raster@EPSG:28992@png8
has tilesets for level 8 and 9, the order is 0 and 1

`<TileSets profile="local"><TileSet href="http://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0/top25raster@EPSG%3A28992@png8/9" units-per-pixel="6.72" order="0"/><TileSet href="http://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0/top25raster@EPSG%3A28992@png8/10" units-per-pixel="3.36" order="1"/></TileSets>`

in TMS.doGetTile  order is used to locate a tileset: this is wrong.

**Comment by LindaVels** [comment]
Is drie maanden geleden al gerealiseerd

**Comment by LindaVels** [comment]
Te testen met PDOK top25raster

**Comment by HermanAssink** [comment]
Bijna goed, bij het uitzoomen naar de schaalstap waarbij de service geen data heeft wordt het kaartbeeld niet weggehaald:
![image](https://cloud.githubusercontent.com/assets/2979044/18172248/fce919f2-7064-11e6-867c-5bbe51b8315f.png)

**Comment by LindaVels** [comment]
Zolang er nog geen nieuw plaatje voor een kaartlaag is blijft het oude plaatje staan (dit geld voor alle kaartlagen). Bij een WMS krijg je een leeg plaatje terug als je buiten de schaalgrenzen komt. Bij een TMS krijg je ws niets terug zodat het oude plaatje blijft staan.

**Comment by LindaVels** [comment]
Dit is het gedrag van OL, niet eenvoudig aanpasbaar.
