### ISSUE TITLE
client afhandeling refresh actie mapdefinition

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#227]

**Comment by LindaVels** [comment]
waarschuwingsscherm "mapdefinition gewijzigd, refresh

**Comment by HermanAssink** [comment]
Kan gesloten. Na aanpassing in de Composer moet de gebruiker zo nodig door de beheerder geïnformeerd worden dat de viewer herstart moet worden. Probleem is bovendien niet volledig oplosbaar, namelijk voor requests die niet via de viewer proxy lopen.
