### ISSUE TITLE
label servicelaag null dan  ""

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#230]
Het label van een servicelaag mag leeg gelaten worden in de Geoide Composer. De Geoide Viewer kan hier nog niet mee omgaan aangezien een null waarde leidt tot een exceptie

**Comment by LindaVels** [comment]
Opgelost in api van admin zodat er geen null waardes in de json terecht komen
label: (serviceLayer.label ? serviceLayer.label : "")

**Comment by HermanAssink** [comment]
Oké
