### ISSUE TITLE
Feature Info op kadastrale-percelen (PDOK) blijft leeg

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-commons#233]
Er komt een leeg popup venster

**Comment by LindaVels** [comment]
Dit komt omdat er gebruik gemaakt wordt van een cosurvey-sql feature type zonder een query attribuut (deze krijgt de wfs van de bijbehorende cosurvey-sql laag)

**Comment by LindaVels** [comment]
Nogmaals onderzoeken

**Comment by LindaVels** [comment]
Na nogmaals testen geconstateerd dat de identify wel werkt op de PDOK percelen wfs

**Comment by LindaVels** [comment]
identfy werkt alleen op zichtbare lagen

**Comment by HermanAssink** [comment]
Heb niet kunnen testen want kaart service werkt niet

**Comment by HermanAssink** [comment]
Werkt nu goed
