### ISSUE TITLE
Grootte van Feature Info venster niet aanpasbaar

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-commons#234]

**Comment by LindaVels** [comment]
resizable gemaakt

**Comment by LindaVels** [comment]
werkt niet in IE

**Comment by LindaVels** [comment]
resizable wordt niet door IE ondersteund, 
Oplossing: window kleiner, inhoud scrallable

**Comment by HermanAssink** [comment]
Werkt goed. Lettertype kan kleiner, dan hoef je minder snel te scollen.

**Comment by LindaVels** [comment]
lettertype iets kleiner gemaakt

**Comment by HermanAssink** [comment]
Kan misschien nog kleiner,maar laat maar zo.
