### ISSUE TITLE
Titelbalk van FI venster buiten beeld te slepen en daarna niet meer te pakken

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-commons#235]

**Comment by LindaVels** [comment]
Wanneer de top of left van het panel zekere waardes overschrijden worden deze aangepast zodat je het panel niet offscreen kan slepen

**Comment by LindaVels** [comment]
werkt niet in IE

**Comment by LindaVels** [comment]
werkt wel voor top en left, Deze zijn het belangrijkste. de positie na buitenbeeld slepen van top gezet op  40px, anders komt het schermpje onder de knoppenbalk

**Comment by HermanAssink** [comment]
Werkt goed
