### ISSUE TITLE
Probleem printen

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#236]

**Comment by LindaVels** [comment]
Printen geeft foutmelding in laatste versie van de viewer

**Comment by LindaVels** [comment]
token werd niet meegenomen met printen -> geeft print fout

**Comment by LindaVels** [comment]
Nieuwe versie uitrollen op test

**Comment by HermanAssink** [comment]
Ik krijg nog een foutmelding: (betreft PDOK kad.percelen, svg probleem?)
![image](https://cloud.githubusercontent.com/assets/2979044/18119901/343876d6-6f5d-11e6-95b5-57be825a9253.png)

**Comment by LindaVels** [comment]
Inderdaad hoogstwaarschijnlijk svg probleem

**Comment by LindaVels** [comment]
In dit geval speelt er een ander probleem: serviceEndpoint kan met of zonder "?" erachter in de composer worden geconfigureerd. Wanneer er een ? achteraan komt dan resulteert dat in een url met ?? en dus tot een fout. Afspraak: serviceEnpoint altijd zonder ? aanleveren aan geoideviewer.

**Comment by LindaVels** [comment]
Ook in de WMSservicetype van geoide wordt er nu rekening gehouden met wel of geen ? in endpoint

**Comment by HermanAssink** [comment]
Bij printen code=003 als fout in CRS

**Comment by LindaVels** [comment]
uitzoeken

**Comment by LindaVels** [comment]
De kadastrale percelen service was nog geconfigureerd met een  https url. Als dit wordt gewijzigd in http is het probleem opgelost en verschijnt de print.

**Comment by HermanAssink** [comment]
Is dit ook de oorzaak bij KKG?

**Comment by LindaVels** [comment]
Nee andere oorzaak nl logo.png.png ipv logo.png
