### ISSUE TITLE
Suggereren vanaf twee karakters om te voorkomen dat suggestielijst niet klopt met ingevoerde karakters

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-commons#245]

**Comment by LindaVels** [comment]
Ook bekijken of het probleem van volgorde request responses kan worden opgelost

**Comment by LindaVels** [comment]
geen resultaten tonen wanneer er nog een nieuw request loopt,
pas beginnen met zoeken nadat er twee characters zijn ingevoerd
