### ISSUE TITLE
Digitaliseer punt kan niet 'uitgezet' worden

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-commons#266]
https://github.com/IDgis/CRS2/issues/212

**Comment by ejmeulenkamp** [comment]
Het hoeft voor mij niet perse veranderd te worden. Ik wil alleen maar voorkomen dat er helpdeskmeldingen komen. Gebruikers weten nu het verschil niet tussen knoppen die wel 'uitschakelbaar' zijn en knoppen die dat niet zijn. We kunnen ook eerst afwachten of er commentaar op komt.

**Comment by HermanAssink** [comment]
Knop gaat uit als je een andere knop kiest. Hier is nooit een melding over geweest. Lijkt me geen probleem

**Comment by ejmeulenkamp** [comment]
Oké
