### ISSUE TITLE
WMS luchtfoto ODRU werkt niet

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-commons#271]
Service failures zichtbaar maken in de viewer.

zie aanleiding ``"WMS luchfoto ODRU werkt niet"``:
https://github.com/IDgis/geoide-admin/issues/235

**Comment by HermanAssink** [comment]
Kan gesloten. Nieuw issue voor foutafhandeling services gemaakt

**Comment by robstek** [comment]
https://github.com/IDgis/geoide-commons/issues/272
