### ISSUE TITLE
Luchtfoto ODRU  geeft geen beeld

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-commons#275]
Ook niet als je het browserwindow verkleint. 
Er staat geen foutmelding in de log v.d. viewer service

**Comment by robstek** [comment]
1. het browser venster moet flink verkleint worden want de viewer vraagt getmap aan met een hoogte groter dan het browser venster.

2. als de service een fout geeft:
```
<ServiceExceptionReport>
<ServiceException code="InvalidParameterValue" locator="height">Height out of range. Maximum height: 1000</ServiceException>
</ServiceExceptionReport>
```
zie je dat in browser ``network``venster  als een http 200 code.
Het effect is dat de viewer het vorige goed ontvangen plaatje blijft gebruiken ook als je verder inzoomt.

**Comment by HermanAssink** [comment]
Welke height en width vraagt de viewer precies op als de viewer fullscreen (HD = 1920x1080 px ) draait?

Kun je OpenLayers ook instrueren om geen rand buiten beeld op te halen?

**Comment by robstek** [comment]
http://odru.ecw-hosting.nl/lufo/services?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=Bunnik&SRS=EPSG%3A28992&STYLES=&*WIDTH=2507&HEIGHT=1395*&BBOX=126208.31999999998%2C445677.11999999994%2C159902.4%2C464425.92

**Comment by HermanAssink** [comment]
In de lufo WMS is ingesteld: MaxWidth=2900 en wms:MaxHeight=1400. 
Dit blijkt voldoende voor de viewer en geeft geen memory fout in de WMS

**Comment by LindaVels** [comment]
Heb hier gewoon beeld zowel op de hoofdlaag als op de sublagen. 
De laag die stond geconfigureerd (Bunnik) werd bedekt door de archeologie laag en  leek daarom niet zichtbaar...denk ik

**Comment by LindaVels** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9080474/19241380/b1dd9140-8f0e-11e6-9125-9178eca22f5a.png)

**Comment by HermanAssink** [comment]
Bij mij werd de luchtfoto afgedekt door een laag van Overijssel. Opgelost.
