### ISSUE TITLE
Viewer draait servicelagen in een laag in volgorde om

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-commons#277]
In de viewer legenda is de volgorde omgekeerd zoals die in de composer is samengesteld :
Bovenste servicelaag in de composer staan onderin in de viewer legenda

**Comment by HermanAssink** [comment]
Is nog niet opgelost

**Comment by LindaVels** [comment]
In viewer wordt alle layers en servicelayers omgedraaid voor de legenda in de composer json-api werden alleen de layers omgekeerd opgeleverd

**Comment by LindaVels** [comment]
De manier waarop de servicelayers nu worden aangeleverd door de composer resulteert ook in een verkeerde tekenvolgorde in de viewer. Ergo: de Composer moet worden aangepast.

**Comment by LindaVels** [comment]
Composer api aangepast en alles werkt naar behoren

**Comment by HermanAssink** [comment]
Oké
