### ISSUE TITLE
Legengraphic niet zichtbaar in viewer

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-commons#283]
bij demo composer voor bijv ozhz zijn bij geen enkele servicelaag de legendgraphics zichtbaar.
Composer: http://composer-demo.geoide.nl/layers (1.0.1)
Viewer: http://viewer-demo.geoide.nl/geoide/demo-ozhz-publiek-ev (1.0.13-snapshot)

**Comment by robstek** [comment]
Bijvoorbeeld laag Inrichtingen:
In het LG plaatje staat de url 
http://viewer-demo.geoide.nl/image/http:%2F%2Fozhz.geoide.nl%2Fozhz%2Fservices%3Frequest=GetLegendGraphic&version=1.1.1&service=WMS&layer=inrichtingen&style=default&format=image%2Fpng

met de hand gedecodeerd geeft wel een plaatje in de browser:
http://ozhz.geoide.nl/ozhz/services?request=GetLegendGraphic&version=1.1.1&service=WMS&layer=inrichtingen&style=default&format=image/png

**Comment by HermanAssink** [comment]
Staat er een foutmelding in de log v.d. viewer, welke?

**Comment by LindaVels** [comment]
Zie issue over play routing met urls in de Kennisbank  zie https://github.com/IDgis/kennisbank/issues/12
