### ISSUE TITLE
Probleem internal url bij printen

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#285]

**Comment by LindaVels** [comment]
nieuwe versie op de ozhz demo acceptatie omgeving geïnstalleerd en getest

**Comment by HermanAssink** [comment]
Ik krijg geen response als ik op de print knop klik.

**Comment by LindaVels** [comment]
Heb je een https service in je configuratie??

In de log file: 
### INFO   | jvm 1    | 2016/12/13 14:33:40 | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO   | jvm 1    | 2016/12/13 14:33:40 | 	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source) ~[na:1.8.0_101]
INFO   | jvm 1    | 2016/12/13 14:33:40 | 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[na:1.8.0_101]
INFO   | jvm 1    | 2016/12/13 14:33:40 | 	at java.security.cert.CertPathBuilder.build(Unknown Source) ~[na:1.8.0_101]
```
