### ISSUE TITLE
75 search tool for viewer

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#75]

**Comment by LindaVels** [comment]
Uitzoeken in oude cosurvey code of naast zoomen ook wordt gehighlighted

**Comment by LindaVels** [comment]
In de oude methode ZoomNaarFeatures in het vb project wordt alleen maar gezoomd en niet gehighlighted

**Comment by HermanAssink** [comment]
Is het mogelijk om te laten zien wat je moet intypen, bijv door de eerste 10 hits bij een lege zoekstring te laten zien? Ik heb anders geen idee hoe ik dit kan testen met een leeg veld. en ik ben denk ik niet de enige...

**Comment by LindaVels** [comment]
Ik neem aan dat de eindgebruikers wel weten wat ze in moeten typen. Wat ik altijd doe is een identify op de laag en vervolgens kijken welke waarden er teugkomen voor het zoekveld.

**Comment by LindaVels** [comment]
format bij label in geoide-admin (voorbeeld waarde)
en
max n features ophalen van wfs in viewer

**Comment by LindaVels** [comment]
NB test omgeving stuk?

**Comment by LindaVels** [comment]
Voorbeeld van format in labels op testomgeving ingevoerd

**Comment by HermanAssink** [comment]
Suggestielijst bij afdelingen werkt snel, maar niet bij percelen.
Ander punt: suggestielijst wordt niet weggehaald bij selecteren van een andere zoekingang.

**Comment by LindaVels** [comment]
Bij percelen zat een fout in de configuratie, nl niet ft perceel maar label was gekozen. label is een hulp veld bij cosurvey-sql lagen voor het al dan niet tonen van labels

**Comment by LindaVels** [comment]
versie 1.0.12-SNAPSHOT suggestie lijst wordt leeg gemaakt bij kiezen nieuwe zoekingang

**Comment by HermanAssink** [comment]
Suggesties zijn lekker snel! 
Wat is de impact van het sorteren van de suggesties?
Bug: Bij het verwijderen van ingetypte karakters  (met backspace) wordt de suggestielijst niet ververst.

**Comment by HermanAssink** [comment]
Ik krijg suggesties die niet horen bij de ingetypte tekst:
![image](https://cloud.githubusercontent.com/assets/2979044/18119352/8229e210-6f5a-11e6-8ba3-553ec1e2c8d8.png)

**Comment by LindaVels** [comment]
ipv maxFeatures count bij WFS2.0.0 geïmplementeerd

**Comment by LindaVels** [comment]
hints worden nu ook geüpdated bij deleten van van laatste karakter(s) in zoekveld

**Comment by LindaVels** [comment]
Voor het sorteren van de suggesties heb ik aan de query een order by clause opgenomen, dit leidt echter tot een foutmelding omdat je geen oreder by  in inner query kan hebben.
Nu worden de suggestie aan de client kant gesorteerd

**Comment by HermanAssink** [comment]
Er komen bij de suggesties ook resultaten die niet horen bij de ingetypte tekst:
![image](https://cloud.githubusercontent.com/assets/2979044/18172451/bf20c6c8-7065-11e6-8416-459f4e2c2404.png)

**Comment by LindaVels** [comment]
Zie #245
