### ISSUE TITLE
79 GetLegendGraphic from WMS for use in TOC

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#79]

**Comment by LindaVels** [comment]
werken met legend url in servicelayer config uit geoide-admin

**Comment by LindaVels** [comment]
de geoide-admin vult de legendUrl in bij een servielayer. Dit is een url naar een locatie op de server of een GetLegendGraphic url.

Let wel: gebruik bij GetLegendGraphic url variabele voor service base in de json, vb:
"legendUrl": <code>"${crs.serviceEndpointBase}</code>/crs-deegree-webservices/services/crs2_wms?request=GetLegendGraphic&version=1.3.0&service=WMS&layer=afdelingen&style=afdelingen&format=image/png"

**Comment by HermanAssink** [comment]
Gebruik v.d. variabele ${crs.serviceEndpointBase} gaat toch niet werken met andere services dan die van CRS/CA?

**Comment by LindaVels** [comment]
Inderdaad dit gaat alleen werken voor de CRS/CA  service lagen

**Comment by HermanAssink** [comment]
Dus kunnen we deze variabele niet gebruiken?

**Comment by LindaVels** [comment]
In de geoide-admin is toch bekend welke lagen co-survey sql lagen zijn. 
Wanneer we deze variabele niet gebruiken is het niet mogelijk om dezelfde configuratie op zowel test als prod te gebruiken, zonder ook de legendGraphicUrls aan te passen.

**Comment by robstek** [comment]
Geoide-admin: als deze variabele in de Service definitie staat, kan de admin er geen lagen bij vinden. Ook de legengraphic wordt dan niet zichtbaar als plaatje (De url wordt wel opgeslagen).
Dan moet deze env. var ook bij de admin bekend zijn of in zijn configuratie worden opgenomen.

**Comment by HermanAssink** [comment]
geoide-admin genereert toch url's naar zijn eigen instantie, die verschillend is voor test en prod? Dan zijn dat toch vanzelf de juiste url's? Voor off-line gebruik van json files moet de legenda plaatjes apart gedownload kunnen worden en moet de link bij de layer wijzen naar een file op schijf.

**Comment by LindaVels** [comment]
klopt, na overleg met Rob besloten om de urls zoals ze in de geoide-admin zijn ingevoerd (gegenereerd) te gebruiken zonder gebruik te maken van een variabele
