### ISSUE TITLE
82 Redlining in viewer  build

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#82]

**Comment by erikorbons** [comment]
Werkzaamheden:

- [ ] "Renderen" van overlays bestaande uit een box met een pijl, waarbij de box een variabele offset heeft tov het ankerpunt.
- [ ] Interactie voor het tekenen / toevoegen van overlays (dmv draw point)
- [ ] Bewerken van overlays: verplaatsen overlay en verplaatsen box tov ankerpunt.
- [ ] Bewerken tekst en resizen box obv hoogte tekst
- [ ] Overlays beheren in Viewer component: overlay toevoegen / verwijderen
- [ ] Interactie voor selectie en verwijderen van overlays
- [ ] Overlays coderen in print request en naar server sturen
- [ ] Tekenen en bewerken van "normale" geometrie middels interacties
- [ ] Selecteren en verwijderen van "normale" geometrie middels interacties
- [ ] Geometrie coderen in print request en naar server sturen
- [ ] Geometrie opnemen in afdruk
- [ ] Overlays opnemen in afdruk
