### ISSUE TITLE
84 Drag and drop TOC

### ISSUE THREAD

**Issue by LindaVels** [IDgis/geoide-commons#84]

**Comment by LindaVels** [comment]
- [ ] onderzoek /overleg beste oplossing

**Comment by HermanAssink** [comment]
Onderzoek/overleg op korte termijn uitvoeren zodat we weten waar we aan toe zijn

**Comment by LindaVels** [comment]
dnd in TOC geïmplementeerd resterende vraagpunten
- [ ] Wanneer alle lagen naar een groep worden gesleept en er geen data-layer meer in de root staat dan is het niet meer mogelijk om een laag naar root niveau te slepen
- [ ]  Droppen gebeurt altijd na een laag

**Comment by HermanAssink** [comment]
Werkt niet binnen CRS

**Comment by LindaVels** [comment]
uitzoeken

**Comment by LindaVels** [comment]
Werkt nu ook in IE9 binnen CRS2

**Comment by HermanAssink** [comment]
Gefeliciteerd!
